import { Injectable } from '@angular/core';
import { BonusStructure } from './bonusStructure';

@Injectable({
  providedIn: 'root'
})
export class BonusService {

  bonusList: BonusStructure[] = [
    {
      id: 1,
      image: 'assets/card-thumbnails/robot-generator.png',
      imageAlt: 'cartoon robot generated by robohash.org',
      heading: 'Robot generator',
      description: 'Generates an image of a robot based on keywords entered by the user, courtesy of Robohash.org.',
      componentReference: 'robotGenerator'
    },
    {
      id: 2,
      image: 'assets/card-thumbnails/scenario wheel.png',
      imageAlt: 'screen grab of concentric circles each containing four different keywords',
      heading: 'Selection wheel',
      description: 'An animated trio of concentric circles which spin in opposite directions to select a random combination of options.',
      componentReference: 'scenarioWheel'
    },
    {
      id: 3,
      image: 'assets/card-thumbnails/horoscope.png',
      imageAlt: 'screen grab of a horoscope generator',
      heading: 'Random horoscope generator',
      description: 'Uses javascript to animate the appearance of a random humorous horoscope.',
      componentReference: 'horoscope'
    }
  ]

  getAllBonusMaterials(): BonusStructure[] {
    return this.bonusList;
  }

  constructor() { }
}
